# This file will be included by the Makefile under the project directory.

FLOAT_O := $(FLOAT:.a=.o)
FLOAT_VFPRINTF_O := $(dir $(FLOAT))FLOAT_vfprintf.o

FLOAT_A_OBJ := $(FLOAT_O) $(FLOAT_VFPRINTF_O)

$(FLOAT): $(FLOAT_A_OBJ)
	ar r $@ $^

# TODO: complete the following rules

CFLAGS = -m32 -O2 -fno-builtin -I lib-common

$(FLOAT_O):

$(FLOAT_VFPRINTF_O):

